#!/bin/bash
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (C) 2025 aarchd
# Copyright (C) 2025 Deepak Meena <notwho53@gmail.com>
#

set -e

SAVEDIR="."
WORKDIR="./work"
CONF="/etc/mkinitcpio.aarchd.conf"

usage() {
    echo "Usage: $0 [--clean]"
    exit 1
}

if [[ $# -eq 0 ]]; then
    echo "[+] Creating temporary directory at $WORKDIR"
    mkdir -p "$WORKDIR"

    echo "[+] Generating initramfs content using mkinitcpio..."
    KERNEL_VERSION=$(printf '%s\n' /lib/modules/* | xargs -n1 basename | sort -Vr | head -n1)
    mkinitcpio -c "$CONF" -d "$WORKDIR" -k "$KERNEL_VERSION"

    echo "[+] Removing unneeded files..."
    rm -rf "$WORKDIR/usr/lib/modules/"
    echo "  -> Removed: usr/lib/modules"

    echo "[+] Removing root mount handler..."
    sed -i 's/^\(mount_handler=\)default_mount_handler/\1:/' "$WORKDIR/init"

    echo "[+] Creating gzip-compressed initramfs..."
    (cd "$WORKDIR" && find . | cpio -o -H newc | gzip -9 -c) > "$SAVEDIR/aarchd-initrd.img-gz"
    echo "  -> Saved: $SAVEDIR/aarchd-initrd.img-gz"

    echo "[+] Creating lz4-compressed initramfs..."
    (cd "$WORKDIR" && find . | cpio -o -H newc | lz4 -9 -l -c) > "$SAVEDIR/aarchd-initrd.img-lz4"
    echo "  -> Saved: $SAVEDIR/aarchd-initrd.img-lz4"

    echo "[+] Done."
    exit 0
fi

if [[ "$1" == "--clean" ]]; then
    echo "[+] Cleaning $WORKDIR..."
    rm -rf "$WORKDIR"
    echo "  -> Done."
    exit 0
else
    usage
fi
