name: shellcheck

on:
  push:
    paths:
      - aarchd-mkinitfs
      - halium.initcpio_hook
  pull_request:
    paths:
      - aarchd-mkinitfs
      - halium.initcpio_hook

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: Install deps
        run: sudo pacman -Sy git shellcheck --noconfirm --needed

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: shellcheck
        run: |
          echo "Running shellcheck on aarchd-mkinitfs"
          shellcheck aarchd-mkinitfs
          echo "Diff output for aarchd-mkinitfs"
          shellcheck aarchd-mkinitfs -f diff
          echo "Running shellcheck on halium.initcpio_hook"
          shellcheck halium.initcpio_hook
          echo "Diff output for halium.initcpio_hook"
          shellcheck halium.initcpio_hook -f diff
